### ISSUE TITLE
Dynamic credential request

### ISSUE THREAD

**Issue by georgepadayatti** [openid/OpenID4VCI#407] opened 2024-10-24 12:03 UTC
This is regarding the implementation of the [Section 5.1.5 Dynamic Credential Request](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-ID1.html#name-dynamic-credential-request). I am unsure if I should raise this question here or in OpenID4VP.

Dynamic credential request is for situations when an issuer requires verifications from the holder, before issuing the credential. 

Here the issuer has alternating roles: issuer -> verifier -> issuer.

The verifier can specify `direct_post` as a way to receive the authorisation response containing the presentation submission. As per the [OpenID4VP spec Section 6.2](https://openid.net/specs/openid-4-verifiable-presentations-1_0-ID2.html#name-response-mode-direct_post), it says the response endpoint after successfully processing the request must respond with 200 response. It may optionally contain a `redirect_uri`. If a `redirect_uri` is present, the wallet must redirect the user agent to that URI. 

<img width="770" alt="Screenshot 2024-10-24 at 5 18 09 PM" src="https://github.com/user-attachments/assets/0d9818b7-4525-427e-808a-214e8c7c253e">

In the case of dynamic credential request, is it correct to understand the following:

Upon receiving the authorisation response, the verifier seizes being a verifier, therefore doesn't have to send a 200 response with/without `redirect_uri` and becomes an issuer and continues with the issuer flow of returning an [authorisation response](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-ID1.html#section-5.2) with 302 redirects containing code in query params

Is this the correct interpretation?

**Comment by c2bo** [comment] 2024-10-24 18:08
Seems to be related to https://github.com/openid/OpenID4VCI/issues/360? I think some of the discussion and links provided there might help, especially this proposal https://bmi.usercontent.opencode.de/eudi-wallet/eidas-2.0-architekturkonzept/flows/Presentation-During-Issuance/.

**Comment by Sakurann** [comment] 2024-10-28 20:19
closing this as a duplicate of #360

**Closed by Sakurann** 2024-10-28 20:19 UTC
